name: home_services_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  csv: ^5.1.1
  permission_handler: ^11.3.1
  intl: ^0.18.1
  http: ^1.4.0
  url_launcher: ^6.2.5
  mask_text_input_formatter: ^2.5.0
  fl_chart: ^0.64.0
  share_plus: ^11.0.0


  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.2.7
  firebase_analytics: ^11.1.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # Media
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  video_player: ^2.8.1
  file_picker: ^10.2.0

  # Maps and Location
  geolocator: ^14.0.1

  geocoding: ^2.1.0
  google_maps_flutter: ^2.6.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_photon: ^2.0.0
  flutter_nominatim: ^0.0.1+2

  # Ads
  google_mobile_ads: ^6.0.0

  # Environment Config
  flutter_dotenv: ^5.1.0

  # App Icon
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/app_icon.jpg

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.jpg"
